"""
Stub configuration to maintain backward compatibility.
Delegates everything to src/core/config.py.
"""

from src.core.config import (
    BASE_DIR,
    DATA_DIR,
    TESTDATA_DIR,
    WIKI_DIR,
    VECTORSTORE_DIR,
    MOCK_STORAGE_DIR,
    MOCK_DRIVE_DIR,
    MOCK_SEVDESK_FILE,
    LOCAL_LLM_PROVIDER,
    OLLAMA_BASE_URL,
    LM_STUDIO_BASE_URL,
    LM_STUDIO_ENDPOINTS,
    LM_STUDIO_API_TOKENS,
    LM_STUDIO_MODELS,
    LLM_MAX_IN_FLIGHT_PER_ENDPOINT,
    LLM_REQUEST_TIMEOUT,
    LLM_FAILURE_COOLDOWN,
    DEFAULT_LLM_MODEL,
    DEFAULT_EMBEDDING_MODEL,
    PERSONA_PROFILE_FILE,
    SKR_MAPPING_FILE,
    CHECKPOINT_FILE,
)
